services:
  web:
    image: ahersa/web-inmobiliario:latest
    container_name: inmobiliario-web
    restart: always
    environment:
      - SCRAPINGANT_API_KEY=${SCRAPINGANT_API_KEY}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - TZ=Europe/Madrid
      - FLASK_CMD=gunicorn --bind 0.0.0.0:5000 -w 3 app:app  # Comando de producción
    networks:
      - flask_network
      - reverse-proxy
    depends_on:
      postgres:
        condition: service_healthy

  shiny:
    image: ahersa/shiny-inmobiliario:latest
    container_name: inmobiliario-shiny
    restart: always
    environment:
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
      - reverse-proxy
    depends_on:
      postgres:
        condition: service_healthy
  
  fastapi_scrapy:
    build: ./fastapi_scrapy
    container_name: inmobiliario-fastapi_scrapy
    restart: unless-stopped
    # Esto mantiene el contenedor en ejecución sin hacer nada.
    environment: 
      - SCRAPINGANT_API_KEY=${SCRAPINGANT_API_KEY}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: inmobiliario-postgres
    restart: always
    environment:
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - inmobiliario-tools_postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - flask_network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d inmobiliario_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  flask_network: {}
  reverse-proxy:
    external: true

volumes:
  inmobiliario-tools_postgres_data:
    external: true
